ignores:
  - '@commitlint/*'
  - '@semantic-release/*'
  - '@size-limit/*'
  - '@types/*'
  - '@typescript-eslint/parser'
  - jest-*
  - pnpapi
  - rimraf # https://github.com/depcheck/depcheck/issues/776
  - semantic-release
  - ts-jest
  - tslib
