name: pull-request
on:
  pull_request:
    types: [opened, synchronize]
  merge_group:

jobs:
  code:
    uses: cyberuni/.github/.github/workflows/pnpm-verify.yml@main
    with:
      os: '["ubuntu-latest"]'
      skip-playwright: true

  publish-gate:
    if: startsWith(github.head_ref, 'changeset-release/')
    uses: cyberuni/.github/.github/workflows/pnpm-publish-gate.yml@main
    permissions:
      contents: read
